adding log file support

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -1,4 +1,4 @@
-name: Service Workflow
+name: assignment3
 
 on:
   push:
@@ -28,9 +28,24 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+      - name: Generate log.txt
+        run: |
+          echo "Workflow start time: $(date --iso-8601=minutes)" > log.txt
+          echo "Submitter: ${GITHUB_ACTOR}" >> log.txt
+
+      - name: Upload log file
+        uses: actions/upload-artifact@v3
+        with:
+          name: log
+          path: log.txt
+
       - name: Build the Docker image
         run: |
-          docker build -t exercise3 .
+          if docker build -t exercise3 .; then
+            echo "Image successfully built" >> log.txt
+          else
+            echo "Image not able to be built" >> log.txt
+          fi
 
       - name: Save Docker image
         run: |
@@ -47,6 +62,12 @@ jobs:
           name: exercise3-image
           path: exercise3.tar
 
+      - name: Upload log file
+        uses: actions/upload-artifact@v3
+        with:
+          name: log
+          path: log.txt
+
   test:
     needs: build
     runs-on: ubuntu-latest
@@ -57,6 +78,7 @@ jobs:
         uses: actions/setup-python@v3
         with:
           python-version: '3.8'
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
@@ -65,12 +87,36 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: exercise3-image
+
       - name: Load Docker image
         run: |
           docker load < exercise3.tar
+
       - name: Run Docker image
         run: |
-          docker run -d -p 8000:8000 exercise3
-          sleep 5
+          docker load < exercise3.tar
+          if docker run -d -p 8000:8000 exercise3; then
+            echo "Container up and running" >> log.txt
+            sleep 5
+          else
+            echo "Container failed to run" >> log.txt
+          fi
+
       - name: Test the service
-        run: pytest -v tests/assn3_tests.py
+        run: |
+          pytest -v tests/assn3_tests.py > assn3_test_results.txt
+          echo "PYTEST_EXIT_CODE=$?" >> $GITHUB_ENV
+
+      - name: Generate log.txt
+        run: |
+          if [ "$PYTEST_EXIT_CODE" -ne 0 ]; then
+            echo "Tests failed" >> log.txt
+          else
+            echo "Tests succeeded" >> log.txt
+          fi
+
+      - name: Upload log file
+        uses: actions/upload-artifact@v3
+        with:
+          name: log
+          path: log.txt
