fix log formats

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -30,15 +30,15 @@ jobs:
       - uses: actions/checkout@v3
       - name: Generate log.txt
         run: |
-          echo "Workflow start time: $(date --iso-8601=minutes)" > log.txt
-          echo "Submitter: Tommy Ben-Shaul" >> log.txt
+          echo "$(date --iso-8601=minutes)" > log.txt
+          echo "Tommy Ben-Shaul" >> log.txt
 
       - name: Build the Docker image
         run: |
           if docker build -t exercise3 .; then
-            echo "Image successfully built" >> log.txt
+            echo "image successfully built" >> log.txt
           else
-            echo "Image not able to be built" >> log.txt
+            echo "image not able to be built" >> log.txt
           fi
 
       - name: Save Docker image
@@ -99,7 +99,7 @@ jobs:
       - name: Test the service
         run: |
           pytest -v tests/assn3_tests.py > assn3_test_results.txt
-          echo "PYTEST_EXIT_CODE=$?" >> $GITHUB_ENV
+          echo "PYTEST_EXIT_CODE=$?"
 
       - name: Upload test results
         uses: actions/upload-artifact@v3
@@ -110,9 +110,9 @@ jobs:
       - name: Generate log for test result
         run: |
           if [ "$PYTEST_EXIT_CODE" -ne 0 ]; then
-            echo "Tests failed" >> log.txt
+            echo "tests succeeded" >> log.txt
           else
-            echo "Tests succeeded" >> log.txt
+            echo "tests failed" >> log.txt
           fi
 
       - name: Upload log file
